### ISSUE TITLE
What is the maximum number of connections?

### ISSUE THREAD

**Issue by luisfpinto** [tewarid/node-tcp-relay#2]
i have followed you code in order to implement that tcp relay. It really works! However, when I have a big server running on my local machine, I have to refresh the page several times in order to get that on the server side. 

I think that maybe is due to the numbers of tcp connections but I'm not really sure. 

Do you have any idea how could I solve it? Thank you in advance!

**Comment by tewarid** [comment]
Only one additional open connection is maintained by the relay client. The relay server currently rejects connection when no open connection is found with relay client. That is why you need to refresh. 

A possible design change in relay server could be to maintain the connection open until relay client has established a new connection.

**Comment by tewarid** [comment]
Relay server is now able to maintain a connection open until relay client has established a new connection. Can you try and see if it solves your problem?

**Comment by luisfpinto** [comment]
Yes, sure. I'll give you feedback this week! ;)

**Comment by luisfpinto** [comment]
I've just tried your solution and It really works nicely! I think It would be great if we can improve in order to get  a faster solution! ;)

**Comment by tewarid** [comment]
Thank you! You mean faster to establish several connections at the same time?

**Comment by tewarid** [comment]
I've just pushed an update that allows setting the number of available connections relay client will maintain with the relay server.

**Comment by luisfpinto** [comment]
Yes! That is exactly what I mean. I will try it tomorrow ;)

**Comment by tewarid** [comment]
Appreciate it. Sorry for taking a long time to get to your original message. I realized I had disabled notifications for watched repos, and that is never a good thing :)

Closing the issue for now. Please reopen if needed.
