### ISSUE TITLE
relay server to multiple local servers

### ISSUE THREAD

**Issue by mishoboss** [tewarid/node-tcp-relay#3]
Hi, great project. It works like a charm. However I need some additional touch to fit my needs. Is it possible the relay server to transmit traffic to multiple different local servers? The idea is to have some token. Clients connect with that token and local servers connect with tokens too. Only clients and server which match a token can communicate with each other. Something like that:

client (token1) <-----> relay server <-----> server (token1) - connection established
client (token1) <-----> relay server <-----> server (token2) - connection NOT established

Is this possible with this module?

**Comment by tewarid** [comment]
Hi. Thank you.

Currently, clients don't need to know or do anything special to use the relay server i.e. they just use a normal TCP socket. Security can be handled by the endpoints as they see fit. If they wan't to use SSL/TLS, they can. If they want to use proprietary encryption, they can.

One way I see to handle what you want to do is to spawn multiple instances of relay client/server, each dedicated to a different local server. 

client <-----> relay server instance 1 <-----> local server 1
client <-----> relay server instance 2 <-----> local server 2

Will that solve your problem? Why not?

**Comment by mishoboss** [comment]
Thanks for the quick reply. Spawning multiple instances would be tricky I think. The problem is I don't know how much local servers there will be. There may be a few thousands.

I think security in this case should be handled at the relay server, not at the endpoints. I don't want all the traffic be broadcasted to all. Do you think this module will fit these needs, or I should look somewhere else. 
Also what about scalability? As I said, there may be thousands or even tens of thousands simultaneously connected local servers and clients. What are the limitations? Ports pool?

**Comment by tewarid** [comment]
The kind of scalability you need is a solved problem with HTTP/S, right?

clients <-----> HTTP/S reverse proxy <-----> multiple relay servers for redundancy and scalability <-----> HTTP/S reverse proxy <-----> Multiple local servers for scalability

**Comment by mishoboss** [comment]
I see. So I go out of the scope of this module. I see you have an example with a reverse proxy in the README. But still can't figure out how this could help on achieving the per-token lock. I'll start reading about your reverse proxy idea, but if you have some free time, I would appreciate if you give me some more technical hints.

**Comment by tewarid** [comment]
> But still can't figure out how this could help on achieving the per-token lock.

One way to tackle that with HTTP/S, is to send the token as a HTTP header (or query parameter) to the local HTTP/S reverse proxy and/or local server. They can then take appropriate actions.

**Comment by mishoboss** [comment]
I continue to bang head here :( Where should reverse proxy server be hosted exactly? And how node-tcp-relay could be used together with http-proxy module in order the proxy to understand HTTP headers and do actions based on that? A simple code example would be hell of a help. Thank you!

**Comment by tewarid** [comment]
Sorry for taking so long to respond. Have you got this figured out? Answering your question on where to host the reverse proxy - one should be hosted between the relay client and server on the private network, and another between relay server and user agents on the internet.

I am planning to add simple listener/callback to relay client and server that should allow applications to intercept and change data as they see fit. Something akin to servlet filters in Java. This may help you build the feature you requested on top of the relay.

**Comment by tewarid** [comment]
The kind of multiplexing requested here is probably best handled using HTTP or HTTP/2.
