### ISSUE TITLE
Handling multiple remote relay servers

### ISSUE THREAD

**Issue by neeksor** [tewarid/node-tcp-relay#4]
Currently the design is 1 central relay server and 1 shared service client that connects to the relay server with 1 exposed internet port that will relay through the shared service client.

Is it possible to have multiple shared service clients and multiple exposed internet ports that map  1:1 with shared service clients?

**Comment by tewarid** [comment]
Have you considered running multiple instances of relay server and client? You can do that via the API or the command line.
