### ISSUE TITLE
I made the free "hypertunnel" service based on this :-)

### ISSUE THREAD

**Issue by berstend** [tewarid/node-tcp-relay#7]
Thanks a lot for `node-tcp-relay`, it's really robust and works well.

For a project I needed a something similar to localtunnel/ngrok with a free server, but for arbitrary TCP/IP services, not just web servers.

As this unfortunately didn't exist I made such service, based on your code. :-)

The documentation can be found here:
https://github.com/berstend/hypertunnel

Exposing e.g. the local port 8000 on the internet is a one liner:
```bash
npx hypertunnel -p 8000 # > Tunneling hypertunnel.ga:29211 > localhost:8000
```

For now things are quite simplistic, for each tunnel request I create a new relayServer (with a dedicated relay-/internetPort pair). In my tests that seems quite scalable, so I guess that's fine for the time being. During tunnel creation client and server exchange a unique secret, to prevent port hijacking from other users. 😄 

Eventually I'd like to hook deeper into `node-tcp-relay` events for better error reporting and to show established connections to the user.

Thanks again! 👍

**Comment by tewarid** [comment]
You're welcome! I'm happy you found `node-tcp-relay` useful and robust for what you needed to do. I'm going to try hypertunnel as soon as the need arises. So, thank you! 😄
